export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';

export const SET_NAV_ACTIONS = 'SET_NAV_ACTIONS';

export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICES_START = 'GET_DEVICES_START';
export const GET_DEVICES_FINISH = 'GET_DEVICES_FINISH';

export const ADD_DEVICE = 'ADD_DEVICE';
export const ADD_DEVICE_START = 'ADD_DEVICE_START';
export const ADD_DEVICE_FINISH = 'ADD_DEVICE_FINISH';
export const ADD_DEVICE_FAIL = 'ADD_DEVICE_FAIL';