export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_FINISH = 'SIGN_IN_FINISH';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_IN_USER = 'SIGN_IN_USER';

export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_FINISH = 'SIGN_UP_FINISH';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_USER = 'SIGN_UP_USER';

export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';

export const SET_NAV_ACTIONS = 'SET_NAV_ACTIONS';
export const SET_NAV_TITLE = 'SET_NAV_TITLE';

export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICES_START = 'GET_DEVICES_START';
export const GET_DEVICES_FINISH = 'GET_DEVICES_FINISH';

export const ADD_DEVICE = 'ADD_DEVICE';
export const ADD_DEVICE_START = 'ADD_DEVICE_START';
export const ADD_DEVICE_FINISH = 'ADD_DEVICE_FINISH';
export const ADD_DEVICE_FAIL = 'ADD_DEVICE_FAIL';

export const GET_CURRENT_DEVICE = 'GET_CURRENT_DEVICE';
export const GET_CURRENT_DEVICE_START = 'GET_CURRENT_DEVICE_START';
export const GET_CURRENT_DEVICE_FINISH = 'GET_CURRENT_DEVICE_FINISH';

export const EDIT_DEVICE = 'EDIT_DEVICE';
export const EDIT_DEVICE_START = 'EDIT_DEVICE_START';
export const EDIT_DEVICE_FINISH = 'EDIT_DEVICE_FINISH';
export const EDIT_DEVICE_FAIL = 'EDIT_DEVICE_FAIL';

export const GET_CURRENT_SENSOR = 'GET_CURRENT_SENSOR';
export const GET_CURRENT_SENSOR_START = 'GET_CURRENT_SENSOR_START';
export const GET_CURRENT_SENSOR_FINISH = 'GET_CURRENT_SENSOR_FINISH';

export const EDIT_SENSOR = 'EDIT_SENSOR';
export const EDIT_SENSOR_START = 'EDIT_SENSOR_START';
export const EDIT_SENSOR_FINISH = 'EDIT_SENSOR_FINISH';
export const EDIT_SENSOR_FAIL = 'EDIT_SENSOR_FAIL';

export const GET_SENSOR_DATA = 'GET_SENSOR_DATA';
export const GET_SENSOR_DATA_START = 'GET_SENSOR_DATA_START';
export const GET_SENSOR_DATA_FINISH = 'GET_SENSOR_DATA_FINISH';

export const GET_CURRENT_RELAY = 'GET_CURRENT_RELAY';
export const GET_CURRENT_RELAY_START = 'GET_CURRENT_RELAY_START';
export const GET_CURRENT_RELAY_FINISH = 'GET_CURRENT_RELAY_FINISH';

export const EDIT_RELAY = 'EDIT_RELAY';
export const EDIT_RELAY_START = 'EDIT_RELAY_START';
export const EDIT_RELAY_FINISH = 'EDIT_RELAY_FINISH';
export const EDIT_RELAY_FAIL = 'EDIT_RELAY_FAIL';

export const GET_RELAY_DATA = 'GET_RELAY_DATA';
export const GET_RELAY_DATA_START = 'GET_RELAY_DATA_START';
export const GET_RELAY_DATA_FINISH = 'GET_RELAY_DATA_FINISH';